package su2config

// This file is autogenerated using github.com/btracey/su2tools/config_writer/parser/write_options_structs.go based on the output from parse_config.py

// List of all the enumerable types and their options

// RegimeTypeEnum is the Adjoint type
type RegimeTypeEnum int

// PhysicalProblemEnum is the Physical governing equations
type PhysicalProblemEnum int

// MathProblemEnum is the Mathematical problem
type MathProblemEnum int

// KindTurbModelEnum is the Specify turbulence model
type KindTurbModelEnum int

// KindTransModelEnum is the Specify transition model
type KindTransModelEnum int

// InletTypeEnum is the Inlet boundary type
type InletTypeEnum int

// KindAdaptEnum is the Kind of grid adaptation
type KindAdaptEnum int

// AnalyticalSurfdefEnum is the Use analytical definition for surfaces
type AnalyticalSurfdefEnum int

// UnsteadySimulationEnum is the Unsteady simulation
type UnsteadySimulationEnum int

// TimeDiscreFlowEnum is the Time discretization
type TimeDiscreFlowEnum int

// TimeDiscreTne2Enum is the Time discretization
type TimeDiscreTne2Enum int

// TimeDiscreAdjtne2Enum is the Time discretization
type TimeDiscreAdjtne2Enum int

// TimeDiscreAdjlevelsetEnum is the Time discretization
type TimeDiscreAdjlevelsetEnum int

// TimeDiscreAdjEnum is the Time discretization
type TimeDiscreAdjEnum int

// TimeDiscreLinEnum is the Time discretization
type TimeDiscreLinEnum int

// TimeDiscreTurbEnum is the Time discretization
type TimeDiscreTurbEnum int

// TimeDiscreAdjturbEnum is the Time discretization
type TimeDiscreAdjturbEnum int

// TimeDiscreWaveEnum is the Time discretization
type TimeDiscreWaveEnum int

// TimeDiscreFeaEnum is the Time discretization
type TimeDiscreFeaEnum int

// TimeDiscreHeatEnum is the Time discretization
type TimeDiscreHeatEnum int

// TimeDiscrePoissonEnum is the Time discretization
type TimeDiscrePoissonEnum int

// LinearSolverEnum is the Linear solver for the implicit, mesh deformation, or discrete adjoint systems
type LinearSolverEnum int

// LinearSolverPrecEnum is the Preconditioner for the Krylov linear solvers
type LinearSolverPrecEnum int

// AdjturbLinSolverEnum is the Linear solver for the turbulent adjoint systems
type AdjturbLinSolverEnum int

// AdjturbLinPrecEnum is the Preconditioner for the turbulent adjoint Krylov linear solvers
type AdjturbLinPrecEnum int

// GridMovementKindEnum is the Type of mesh motion
type GridMovementKindEnum int

// GustTypeEnum is the Type of gust
type GustTypeEnum int

// GustDirEnum is the Direction of the gust X or Y dir
type GustDirEnum int

// ConvCriteriaEnum is the Convergence criteria
type ConvCriteriaEnum int

// CauchyFuncFlowEnum is the Flow functional for the Cauchy criteria
type CauchyFuncFlowEnum int

// CauchyFuncAdjEnum is the Adjoint functional for the Cauchy criteria
type CauchyFuncAdjEnum int

// CauchyFuncLinEnum is the Linearized functional for the Cauchy criteria
type CauchyFuncLinEnum int

// NumMethodGradEnum is the Numerical method for spatial gradients
type NumMethodGradEnum int

// ConvNumMethodFlowEnum is the No description
type ConvNumMethodFlowEnum int

// ViscNumMethodFlowEnum is the Viscous numerical method
type ViscNumMethodFlowEnum int

// SourNumMethodFlowEnum is the Source term numerical method
type SourNumMethodFlowEnum int

// SlopeLimiterFlowEnum is the Slope limiter
type SlopeLimiterFlowEnum int

// ConvNumMethodAdjEnum is the No description
type ConvNumMethodAdjEnum int

// ViscNumMethodAdjEnum is the Viscous numerical method
type ViscNumMethodAdjEnum int

// SourNumMethodAdjEnum is the Source term numerical method
type SourNumMethodAdjEnum int

// SlopeLimiterAdjflowEnum is the Slope limiter
type SlopeLimiterAdjflowEnum int

// SlopeLimiterTurbEnum is the Slope limiter
type SlopeLimiterTurbEnum int

// ConvNumMethodTurbEnum is the Convective numerical method
type ConvNumMethodTurbEnum int

// ViscNumMethodTurbEnum is the Viscous numerical method
type ViscNumMethodTurbEnum int

// SourNumMethodTurbEnum is the Source term numerical method
type SourNumMethodTurbEnum int

// SlopeLimiterAdjturbEnum is the Slope limiter
type SlopeLimiterAdjturbEnum int

// ConvNumMethodAdjturbEnum is the Convective numerical method
type ConvNumMethodAdjturbEnum int

// ViscNumMethodAdjturbEnum is the Viscous numerical method
type ViscNumMethodAdjturbEnum int

// SourNumMethodAdjturbEnum is the Source term numerical method
type SourNumMethodAdjturbEnum int

// ConvNumMethodLinEnum is the Convective numerical method
type ConvNumMethodLinEnum int

// ViscNumMethodLinEnum is the Viscous numerical method
type ViscNumMethodLinEnum int

// SourNumMethodLinEnum is the Source term numerical method
type SourNumMethodLinEnum int

// SlopeLimiterAdjlevelsetEnum is the Slope limiter
type SlopeLimiterAdjlevelsetEnum int

// ConvNumMethodAdjlevelsetEnum is the Convective numerical method
type ConvNumMethodAdjlevelsetEnum int

// ViscNumMethodAdjlevelsetEnum is the Viscous numerical method
type ViscNumMethodAdjlevelsetEnum int

// SourNumMethodAdjlevelsetEnum is the Source term numerical method
type SourNumMethodAdjlevelsetEnum int

// ConvNumMethodTne2Enum is the Convective numerical method
type ConvNumMethodTne2Enum int

// ViscNumMethodTne2Enum is the Viscous numerical method
type ViscNumMethodTne2Enum int

// SourNumMethodTne2Enum is the Source term numerical method
type SourNumMethodTne2Enum int

// SlopeLimiterTne2Enum is the Slope limiter
type SlopeLimiterTne2Enum int

// ConvNumMethodAdjtne2Enum is the Convective numerical method
type ConvNumMethodAdjtne2Enum int

// ViscNumMethodAdjtne2Enum is the Viscous numerical method
type ViscNumMethodAdjtne2Enum int

// SourNumMethodAdjtne2Enum is the Source term numerical method
type SourNumMethodAdjtne2Enum int

// SlopeLimiterAdjtne2Enum is the Slope limiter
type SlopeLimiterAdjtne2Enum int

// ViscNumMethodWaveEnum is the Viscous numerical method
type ViscNumMethodWaveEnum int

// SourNumMethodWaveEnum is the Source term numerical method
type SourNumMethodWaveEnum int

// ViscNumMethodPoissonEnum is the Viscous numerical method
type ViscNumMethodPoissonEnum int

// SourNumMethodPoissonEnum is the Source term numerical method
type SourNumMethodPoissonEnum int

// ViscNumMethodFeaEnum is the Viscous numerical method
type ViscNumMethodFeaEnum int

// SourNumMethodFeaEnum is the Source term numerical method
type SourNumMethodFeaEnum int

// ViscNumMethodHeatEnum is the Viscous numerical method
type ViscNumMethodHeatEnum int

// SourNumMethodHeatEnum is the Source term numerical method
type SourNumMethodHeatEnum int

// SourNumMethodTemplateEnum is the Source term numerical method
type SourNumMethodTemplateEnum int

// AdjObjfuncEnum is the Adjoint problem boundary condition
type AdjObjfuncEnum int

// GeoModeEnum is the Mode of the GDC code (analysis, or gradient)
type GeoModeEnum int

// SensSmoothingEnum is the Sensitivity smoothing
type SensSmoothingEnum int

// ContinuousEqnsEnum is the Continuous governing equation set
type ContinuousEqnsEnum int

// DiscreteEqnsEnum is the Discrete governing equation set
type DiscreteEqnsEnum int

// OutputFormatEnum is the I/O
type OutputFormatEnum int

// MeshFormatEnum is the Mesh input file format
type MeshFormatEnum int

// GasModelEnum is the Specify chemical model for multi-species simulations
type GasModelEnum int

// DvKindEnum is the Kind of deformation
type DvKindEnum int
